Reading contacts with Nylas SDK
nylas-samples/nylas-hacktoberfest-2022 pull request #46
Opened 2022-10-01 18:45 UTC by danielevilela

Close the issue #8 
## PR Acceptance Criteria

## Guidelines
* [ x] PR follows the [Contributing guidelines](https://github.com/nylas-samples/nylas-hacktoberfest-2022/blob/main/CONTRIBUTION.md)?
* [x ] PR Adheres to our [Code of Conduct](https://github.com/nylas-samples/nylas-hacktoberfest-2022/blob/main/CODE_OF_CONDUCT.md)?
* [x ] Have you checked to ensure there aren't other open Pull Requests for the same update/change?

## Code complete
* [x ] A `README.md` available describing how to setup and test the code?
* [x ] The code sample in the correct location (i.e. `code-sample/email/node/read-email`)?
* [ ] Link added to the repository readme (view `# Code Snippets created by the Nylas Community` with examples) describing what the code sample does for others to try out
* [ ] The code can be run using Github Codespaces, so the maintainer can try out the code sample remotely to ensure everything is working before we accept the PR.

## For PR Reviewer use
* [ ] Purpose of code sample is clear
* [ ] The code sample is readable
* [ ] Steps try out the code are provided
* [ ] Code sample runs on codespaces environment
* [ ] Code works as expected
* [ ] PR labels added

2022-10-03 15:30 UTC, relaxedtomato commented on code-samples/contact/node/read-contacts/readme.md
> +
can we add a comment regarding what the possible output will look like if no errors?

Take a look at this [readme](https://github.com/nylas-samples/node-email-read/blob/main/readme.md) as a reference (view Usage section).

2022-10-03 15:31 UTC, relaxedtomato commented on readme.md
> +- [contact-list-node](/code-samples/contact/node/read-contacts/): Read contacts using Nylas Node SDK and TypeScript
let's consider naming `node-read-contacts` instead of `contact-list-node`

2022-10-03 15:56 UTC, relaxedtomato requested changes

2022-10-03 15:56 UTC, relaxedtomato commented on code-samples/contact/node/read-contacts/src/index.ts
> +    clientId: process.env.CLIENT_ID,
do you get a type error calling `npm start`:
```error TS2345: Argument of type 'string | undefined' is not assignable to parameter of type 'string'.
  Type 'undefined' is not assignable to type 'string'.```
 
Let me know if any workarounds for this, let's address those.

2022-10-03 16:38 UTC, relaxedtomato commented on code-samples/contact/node/read-contacts/src/index.ts
> +    clientId: process.env.CLIENT_ID,
One possible workaround is adding an || operator, so `clientId: process.env.CLIENT_ID || ""`

2022-10-03 16:42 UTC, danielevilela commented on code-samples/contact/node/read-contacts/src/index.ts
> +    clientId: process.env.CLIENT_ID,
Hi,

I'll review your requests and get back at the end of the day.

Yes, you can use an operator or enforce its type: 
```process.env.CLIENT_ID as string```

2022-10-04 01:57 UTC, danielevilela commented on code-samples/contact/node/read-contacts/readme.md
> +
Yes, I can add the result as follow if that's okay: 
![image](https://user-images.githubusercontent.com/5096692/193717965-1829a891-85a3-4919-8ca7-f105dfe79d89.png)

I used Nylas test users and apparently they have no Name or Surname, and you're also not able to change this info in the Dashboard. Is that correct?

2022-10-04 14:13 UTC, relaxedtomato commented on code-samples/contact/node/read-contacts/readme.md
> +
That makes sense @danielevilela - the `Nylas test account` only allows for read-only, so the message `You do not have access to the required scopes` makes sense.

You can actually connect your personal account to try things out as well, but what you have is sufficient. Will review shortly.

2022-10-04 14:15 UTC, relaxedtomato commented on code-samples/contact/node/read-contacts/readme.md
> +  ### In the root folder, reate a .env file with your nylas configuration as follow:
```suggestion
  ### In the root folder, create a .env file with your nylas configuration as follow: 
```

2022-10-04 14:15 UTC, relaxedtomato commented on code-samples/contact/node/read-contacts/readme.md
> +
Add the `#Usage` section when you get a chance, the readme looks good.

2022-10-04 14:16 UTC, relaxedtomato commented
@danielevilela - looks solid, once the `readme.md` includes a `Usage` section, we are good to go!

2022-10-04 15:50 UTC, relaxedtomato requested changes
Once the `readme.md` is updated, I will do a quick test and we should be good to go 🙌

2022-10-05 16:09 UTC, relaxedtomato approved these changes

2022-10-05 18:12 UTC, merged

2022-10-05 18:23 UTC, relaxedtomato commented
Thanks @danielevilela for contributing, happy hacktober 🙌

2022-10-06 16:58 UTC, ashryanbeats commented
Thanks for your contribution @danielevilela!