feat: add create draft
nylas-samples/nylas-hacktoberfest-2022 pull request #59
Opened 2022-10-12 17:34 UTC by MoskalykA

## PR Acceptance Criteria
Closes #27 

## Guidelines
* [x] PR follows the [Contributing guidelines](https://github.com/nylas-samples/nylas-hacktoberfest-2022/blob/main/CONTRIBUTION.md)?
* [x] PR Adheres to our [Code of Conduct](https://github.com/nylas-samples/nylas-hacktoberfest-2022/blob/main/CODE_OF_CONDUCT.md)?
* [x] Have you checked to ensure there aren't other open Pull Requests for the same update/change?
* [x] Ensure you are assigned the issue before creating a PR.
* [x] Only one issue per PR is allowed. This simplifies the code review.

## Code complete
* [x] A `README.md` available describing 1) how to setup, 2) how to test the code and 3) the expected output? Here is an [example](code-samples/account/node/read-account/readme.md). 
* [x] The code sample in the correct location (i.e. `code-sample/email/node/read-email`)?
* [x] Link added to the repository readme (view `# Code Snippets created by the Nylas Community` with examples) describing what the code sample does for others to try out
* [x] The code can be run using Github Codespaces, so the maintainer can try out the code sample remotely to ensure everything is working before we accept the PR.

## For Maintainer Use Only (does not apply to PR Author)
* [ ] Purpose of code sample is clear
* [ ] The code sample is readable
* [ ] Steps try out the code are provided
* [ ] Code sample runs on codespaces environment
* [ ] Code works as expected
* [ ] PR label `hacktoberfest-accepted` added

2022-10-12 22:25 UTC, relaxedtomato requested changes

2022-10-12 22:25 UTC, relaxedtomato commented on code-samples/email/node/create-draft/index.js
> +   clientSecret: process.env.CLIENT_SECRET
have you tested this locally - how do we access these values, do we need to have `dotenv`?

2022-10-13 05:57 UTC, MoskalykA commented
I had forgotten about the famous dotenv

2022-10-13 19:33 UTC, relaxedtomato requested changes
Minor changes, but should be good to go afterwards.

2022-10-13 19:33 UTC, relaxedtomato commented on code-samples/email/node/create-draft/index.js
> +})
This is really close, one thing to note is that the draft is not available in my email unless I add `draft.save();`

Can you consider adding this after creating the draft?

2022-10-13 19:33 UTC, relaxedtomato commented on code-samples/email/node/create-draft/readme.md
> +```
Can we add a `#Usage` section to describe what the desired output is?

Even if its receiving a draft email, that's sufficient to mention with an image:
<img width="589" alt="Screen Shot 2022-10-13 at 3 33 15 PM" src="https://user-images.githubusercontent.com/553578/195692673-b4e299cd-6159-4c45-a137-3d932c3a2671.png">

2022-10-14 17:02 UTC, MoskalykA commented
Is it good?

2022-10-14 21:01 UTC, relaxedtomato commented on code-samples/email/node/create-draft/index.js
> +draft.save()
⚡

2022-10-14 21:02 UTC, relaxedtomato approved these changes

2022-10-14 21:03 UTC, relaxedtomato commented
@MoskalykA thanks for your contribution for Hacktoberfest, consider picking up [another ticket](https://github.com/nylas-samples/nylas-hacktoberfest-2022/issues) or by [suggesting a code sample you like to share](https://github.com/nylas-samples/nylas-hacktoberfest-2022/issues/new/choose)!

2022-10-17 15:18 UTC, merged